// Complete country-to-language mapping for global user support
export const countryLanguageMap: Record<string, { language: string; code: string; flag: string }> = {
  "Afghanistan": { language: "Pashto", code: "ps", flag: "🇦🇫" },
  "Albania": { language: "Albanian", code: "sq", flag: "🇦🇱" },
  "Algeria": { language: "Arabic", code: "ar", flag: "🇩🇿" },
  "Andorra": { language: "Catalan", code: "ca", flag: "🇦🇩" },
  "Angola": { language: "Portuguese", code: "pt", flag: "🇦🇴" },
  "Antigua and Barbuda": { language: "English", code: "en", flag: "🇦🇬" },
  "Argentina": { language: "Spanish", code: "es", flag: "🇦🇷" },
  "Armenia": { language: "Armenian", code: "hy", flag: "🇦🇲" },
  "Australia": { language: "English", code: "en", flag: "🇦🇺" },
  "Austria": { language: "German", code: "de", flag: "🇦🇹" },
  "Azerbaijan": { language: "Azerbaijani", code: "az", flag: "🇦🇿" },
  "Bahamas": { language: "English", code: "en", flag: "🇧🇸" },
  "Bahrain": { language: "Arabic", code: "ar", flag: "🇧🇭" },
  "Bangladesh": { language: "Bengali", code: "bn", flag: "🇧🇩" },
  "Barbados": { language: "English", code: "en", flag: "🇧🇧" },
  "Belarus": { language: "Belarusian", code: "be", flag: "🇧🇾" },
  "Belgium": { language: "Dutch", code: "nl", flag: "🇧🇪" },
  "Belize": { language: "English", code: "en", flag: "🇧🇿" },
  "Benin": { language: "French", code: "fr", flag: "🇧🇯" },
  "Bhutan": { language: "Dzongkha", code: "dz", flag: "🇧🇹" },
  "Bolivia": { language: "Spanish", code: "es", flag: "🇧🇴" },
  "Bosnia and Herzegovina": { language: "Bosnian", code: "bs", flag: "🇧🇦" },
  "Botswana": { language: "English", code: "en", flag: "🇧🇼" },
  "Brazil": { language: "Portuguese", code: "pt", flag: "🇧🇷" },
  "Brunei": { language: "Malay", code: "ms", flag: "🇧🇳" },
  "Bulgaria": { language: "Bulgarian", code: "bg", flag: "🇧🇬" },
  "Burkina Faso": { language: "French", code: "fr", flag: "🇧🇫" },
  "Burundi": { language: "Kirundi", code: "rn", flag: "🇧🇮" },
  "Cambodia": { language: "Khmer", code: "km", flag: "🇰🇭" },
  "Cameroon": { language: "French", code: "fr", flag: "🇨🇲" },
  "Canada": { language: "English", code: "en", flag: "🇨🇦" },
  "Cape Verde": { language: "Portuguese", code: "pt", flag: "🇨🇻" },
  "Central African Republic": { language: "French", code: "fr", flag: "🇨🇫" },
  "Chad": { language: "French", code: "fr", flag: "🇹🇩" },
  "Chile": { language: "Spanish", code: "es", flag: "🇨🇱" },
  "China": { language: "Mandarin Chinese", code: "zh", flag: "🇨🇳" },
  "Colombia": { language: "Spanish", code: "es", flag: "🇨🇴" },
  "Comoros": { language: "Arabic", code: "ar", flag: "🇰🇲" },
  "Congo (Republic)": { language: "French", code: "fr", flag: "🇨🇬" },
  "Costa Rica": { language: "Spanish", code: "es", flag: "🇨🇷" },
  "Croatia": { language: "Croatian", code: "hr", flag: "🇭🇷" },
  "Cuba": { language: "Spanish", code: "es", flag: "🇨🇺" },
  "Cyprus": { language: "Greek", code: "el", flag: "🇨🇾" },
  "Czech Republic": { language: "Czech", code: "cs", flag: "🇨🇿" },
  "Denmark": { language: "Danish", code: "da", flag: "🇩🇰" },
  "Djibouti": { language: "French", code: "fr", flag: "🇩🇯" },
  "Dominica": { language: "English", code: "en", flag: "🇩🇲" },
  "Dominican Republic": { language: "Spanish", code: "es", flag: "🇩🇴" },
  "Ecuador": { language: "Spanish", code: "es", flag: "🇪🇨" },
  "Egypt": { language: "Arabic", code: "ar", flag: "🇪🇬" },
  "El Salvador": { language: "Spanish", code: "es", flag: "🇸🇻" },
  "Equatorial Guinea": { language: "Spanish", code: "es", flag: "🇬🇶" },
  "Eritrea": { language: "Tigrinya", code: "ti", flag: "🇪🇷" },
  "Estonia": { language: "Estonian", code: "et", flag: "🇪🇪" },
  "Eswatini": { language: "Swazi", code: "ss", flag: "🇸🇿" },
  "Ethiopia": { language: "Amharic", code: "am", flag: "🇪🇹" },
  "Fiji": { language: "Fijian", code: "fj", flag: "🇫🇯" },
  "Finland": { language: "Finnish", code: "fi", flag: "🇫🇮" },
  "France": { language: "French", code: "fr", flag: "🇫🇷" },
  "Gabon": { language: "French", code: "fr", flag: "🇬🇦" },
  "Gambia": { language: "English", code: "en", flag: "🇬🇲" },
  "Georgia": { language: "Georgian", code: "ka", flag: "🇬🇪" },
  "Germany": { language: "German", code: "de", flag: "🇩🇪" },
  "Ghana": { language: "English", code: "en", flag: "🇬🇭" },
  "Greece": { language: "Greek", code: "el", flag: "🇬🇷" },
  "Grenada": { language: "English", code: "en", flag: "🇬🇩" },
  "Guatemala": { language: "Spanish", code: "es", flag: "🇬🇹" },
  "Guinea": { language: "French", code: "fr", flag: "🇬🇳" },
  "Guinea-Bissau": { language: "Portuguese", code: "pt", flag: "🇬🇼" },
  "Guyana": { language: "English", code: "en", flag: "🇬🇾" },
  "Haiti": { language: "Haitian Creole", code: "ht", flag: "🇭🇹" },
  "Honduras": { language: "Spanish", code: "es", flag: "🇭🇳" },
  "Hungary": { language: "Hungarian", code: "hu", flag: "🇭🇺" },
  "Iceland": { language: "Icelandic", code: "is", flag: "🇮🇸" },
  "India": { language: "Hindi", code: "hi", flag: "🇮🇳" },
  "Indonesia": { language: "Indonesian", code: "id", flag: "🇮🇩" },
  "Iran": { language: "Persian", code: "fa", flag: "🇮🇷" },
  "Iraq": { language: "Arabic", code: "ar", flag: "🇮🇶" },
  "Ireland": { language: "English", code: "en", flag: "🇮🇪" },
  "Israel": { language: "Hebrew", code: "he", flag: "🇮🇱" },
  "Italy": { language: "Italian", code: "it", flag: "🇮🇹" },
  "Jamaica": { language: "English", code: "en", flag: "🇯🇲" },
  "Japan": { language: "Japanese", code: "ja", flag: "🇯🇵" },
  "Jordan": { language: "Arabic", code: "ar", flag: "🇯🇴" },
  "Kazakhstan": { language: "Kazakh", code: "kk", flag: "🇰🇿" },
  "Kenya": { language: "Swahili", code: "sw", flag: "🇰🇪" },
  "Kiribati": { language: "English", code: "en", flag: "🇰🇮" },
  "Kuwait": { language: "Arabic", code: "ar", flag: "🇰🇼" },
  "Kyrgyzstan": { language: "Kyrgyz", code: "ky", flag: "🇰🇬" },
  "Laos": { language: "Lao", code: "lo", flag: "🇱🇦" },
  "Latvia": { language: "Latvian", code: "lv", flag: "🇱🇻" },
  "Lebanon": { language: "Arabic", code: "ar", flag: "🇱🇧" },
  "Lesotho": { language: "Sesotho", code: "st", flag: "🇱🇸" },
  "Liberia": { language: "English", code: "en", flag: "🇱🇷" },
  "Libya": { language: "Arabic", code: "ar", flag: "🇱🇾" },
  "Liechtenstein": { language: "German", code: "de", flag: "🇱🇮" },
  "Lithuania": { language: "Lithuanian", code: "lt", flag: "🇱🇹" },
  "Luxembourg": { language: "Luxembourgish", code: "lb", flag: "🇱🇺" },
  "Madagascar": { language: "Malagasy", code: "mg", flag: "🇲🇬" },
  "Malawi": { language: "Chichewa", code: "ny", flag: "🇲🇼" },
  "Malaysia": { language: "Malay", code: "ms", flag: "🇲🇾" },
  "Maldives": { language: "Dhivehi", code: "dv", flag: "🇲🇻" },
  "Mali": { language: "French", code: "fr", flag: "🇲🇱" },
  "Malta": { language: "Maltese", code: "mt", flag: "🇲🇹" },
  "Marshall Islands": { language: "English", code: "en", flag: "🇲🇭" },
  "Mauritania": { language: "Arabic", code: "ar", flag: "🇲🇷" },
  "Mauritius": { language: "English", code: "en", flag: "🇲🇺" },
  "Mexico": { language: "Spanish", code: "es", flag: "🇲🇽" },
  "Micronesia": { language: "English", code: "en", flag: "🇫🇲" },
  "Moldova": { language: "Romanian", code: "ro", flag: "🇲🇩" },
  "Monaco": { language: "French", code: "fr", flag: "🇲🇨" },
  "Mongolia": { language: "Mongolian", code: "mn", flag: "🇲🇳" },
  "Montenegro": { language: "Montenegrin", code: "sr", flag: "🇲🇪" },
  "Morocco": { language: "Arabic", code: "ar", flag: "🇲🇦" },
  "Mozambique": { language: "Portuguese", code: "pt", flag: "🇲🇿" },
  "Myanmar": { language: "Burmese", code: "my", flag: "🇲🇲" },
  "Namibia": { language: "English", code: "en", flag: "🇳🇦" },
  "Nauru": { language: "English", code: "en", flag: "🇳🇷" },
  "Nepal": { language: "Nepali", code: "ne", flag: "🇳🇵" },
  "Netherlands": { language: "Dutch", code: "nl", flag: "🇳🇱" },
  "New Zealand": { language: "English", code: "en", flag: "🇳🇿" },
  "Nicaragua": { language: "Spanish", code: "es", flag: "🇳🇮" },
  "Niger": { language: "French", code: "fr", flag: "🇳🇪" },
  "Nigeria": { language: "English", code: "en", flag: "🇳🇬" },
  "North Korea": { language: "Korean", code: "ko", flag: "🇰🇵" },
  "North Macedonia": { language: "Macedonian", code: "mk", flag: "🇲🇰" },
  "Norway": { language: "Norwegian", code: "no", flag: "🇳🇴" },
  "Oman": { language: "Arabic", code: "ar", flag: "🇴🇲" },
  "Pakistan": { language: "Urdu", code: "ur", flag: "🇵🇰" },
  "Palau": { language: "English", code: "en", flag: "🇵🇼" },
  "Panama": { language: "Spanish", code: "es", flag: "🇵🇦" },
  "Papua New Guinea": { language: "Tok Pisin", code: "tpi", flag: "🇵🇬" },
  "Paraguay": { language: "Spanish", code: "es", flag: "🇵🇾" },
  "Peru": { language: "Spanish", code: "es", flag: "🇵🇪" },
  "Philippines": { language: "Filipino", code: "tl", flag: "🇵🇭" },
  "Poland": { language: "Polish", code: "pl", flag: "🇵🇱" },
  "Portugal": { language: "Portuguese", code: "pt", flag: "🇵🇹" },
  "Qatar": { language: "Arabic", code: "ar", flag: "🇶🇦" },
  "Romania": { language: "Romanian", code: "ro", flag: "🇷🇴" },
  "Russia": { language: "Russian", code: "ru", flag: "🇷🇺" },
  "Rwanda": { language: "Kinyarwanda", code: "rw", flag: "🇷🇼" },
  "Saint Kitts and Nevis": { language: "English", code: "en", flag: "🇰🇳" },
  "Saint Lucia": { language: "English", code: "en", flag: "🇱🇨" },
  "Saint Vincent and the Grenadines": { language: "English", code: "en", flag: "🇻🇨" },
  "Samoa": { language: "Samoan", code: "sm", flag: "🇼🇸" },
  "San Marino": { language: "Italian", code: "it", flag: "🇸🇲" },
  "Saudi Arabia": { language: "Arabic", code: "ar", flag: "🇸🇦" },
  "Senegal": { language: "French", code: "fr", flag: "🇸🇳" },
  "Serbia": { language: "Serbian", code: "sr", flag: "🇷🇸" },
  "Seychelles": { language: "English", code: "en", flag: "🇸🇨" },
  "Sierra Leone": { language: "English", code: "en", flag: "🇸🇱" },
  "Singapore": { language: "English", code: "en", flag: "🇸🇬" },
  "Slovakia": { language: "Slovak", code: "sk", flag: "🇸🇰" },
  "Slovenia": { language: "Slovene", code: "sl", flag: "🇸🇮" },
  "Solomon Islands": { language: "English", code: "en", flag: "🇸🇧" },
  "Somalia": { language: "Somali", code: "so", flag: "🇸🇴" },
  "South Africa": { language: "English", code: "en", flag: "🇿🇦" },
  "South Sudan": { language: "English", code: "en", flag: "🇸🇸" },
  "Spain": { language: "Spanish", code: "es", flag: "🇪🇸" },
  "Sri Lanka": { language: "Sinhala", code: "si", flag: "🇱🇰" },
  "Sudan": { language: "Arabic", code: "ar", flag: "🇸🇩" },
  "Suriname": { language: "Dutch", code: "nl", flag: "🇸🇷" },
  "Sweden": { language: "Swedish", code: "sv", flag: "🇸🇪" },
  "Switzerland": { language: "German", code: "de", flag: "🇨🇭" },
  "Syria": { language: "Arabic", code: "ar", flag: "🇸🇾" },
  "Taiwan": { language: "Mandarin Chinese", code: "zh-TW", flag: "🇹🇼" },
  "Tajikistan": { language: "Tajik", code: "tg", flag: "🇹🇯" },
  "Tanzania": { language: "Swahili", code: "sw", flag: "🇹🇿" },
  "Thailand": { language: "Thai", code: "th", flag: "🇹🇭" },
  "Timor-Leste": { language: "Tetum", code: "tet", flag: "🇹🇱" },
  "Togo": { language: "French", code: "fr", flag: "🇹🇬" },
  "Tonga": { language: "Tongan", code: "to", flag: "🇹🇴" },
  "Trinidad and Tobago": { language: "English", code: "en", flag: "🇹🇹" },
  "Tunisia": { language: "Arabic", code: "ar", flag: "🇹🇳" },
  "Turkey": { language: "Turkish", code: "tr", flag: "🇹🇷" },
  "Turkmenistan": { language: "Turkmen", code: "tk", flag: "🇹🇲" },
  "Tuvalu": { language: "English", code: "en", flag: "🇹🇻" },
  "Uganda": { language: "English", code: "en", flag: "🇺🇬" },
  "Ukraine": { language: "Ukrainian", code: "uk", flag: "🇺🇦" },
  "United Arab Emirates": { language: "Arabic", code: "ar", flag: "🇦🇪" },
  "United Kingdom": { language: "English", code: "en", flag: "🇬🇧" },
  "United States": { language: "English", code: "en", flag: "🇺🇸" },
  "Uruguay": { language: "Spanish", code: "es", flag: "🇺🇾" },
  "Uzbekistan": { language: "Uzbek", code: "uz", flag: "🇺🇿" },
  "Vanuatu": { language: "Bislama", code: "bi", flag: "🇻🇺" },
  "Vatican City": { language: "Italian", code: "it", flag: "🇻🇦" },
  "Venezuela": { language: "Spanish", code: "es", flag: "🇻🇪" },
  "Vietnam": { language: "Vietnamese", code: "vi", flag: "🇻🇳" },
  "Yemen": { language: "Arabic", code: "ar", flag: "🇾🇪" },
  "Zambia": { language: "English", code: "en", flag: "🇿🇲" },
  "Zimbabwe": { language: "English", code: "en", flag: "🇿🇼" },
};

export const getLanguageByCountry = (country: string) => {
  return countryLanguageMap[country] || null;
};

export const getCountriesByLanguage = (languageCode: string) => {
  return Object.entries(countryLanguageMap)
    .filter(([_, data]) => data.code === languageCode)
    .map(([country, data]) => ({ country, ...data }));
};

export const getAllCountries = () => Object.keys(countryLanguageMap);

export const getAllLanguageCodes = () => {
  const codes = new Set(Object.values(countryLanguageMap).map(data => data.code));
  return Array.from(codes);
};
